// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSCSS3Bzm3VgbXwA0kyCPWCWqE8D45ZfE',
    appId: '1:1067598059619:web:2f2b2017255289e3cf0056',
    messagingSenderId: '1067598059619',
    projectId: 'auth-4b2ee',
    authDomain: 'auth-4b2ee.firebaseapp.com',
    storageBucket: 'auth-4b2ee.firebasestorage.app',
    measurementId: 'G-W1PEK50LGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnifN3MF5yK1BXgVhEXIw_HcQ4_eVNG9c',
    appId: '1:1067598059619:android:4bb6766badb2161ccf0056',
    messagingSenderId: '1067598059619',
    projectId: 'auth-4b2ee',
    storageBucket: 'auth-4b2ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWS3EzVPZBtn7t6V20eaMKe5lTgACbqk',
    appId: '1:1067598059619:ios:db172e31c152c3bbcf0056',
    messagingSenderId: '1067598059619',
    projectId: 'auth-4b2ee',
    storageBucket: 'auth-4b2ee.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

}